apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-react
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sm-abdullah/demoReact.git
    targetRevision: HEAD
    path: demo-react/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true