apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-react
  labels:
    app: demo-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-react
  template:
    metadata:
      labels:
        app: demo-react
    spec:
      containers:
      - name: demo-react
        image: smabdullah/demo-react:${VERSION}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15