apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-react
  labels:
    app: demo-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-react
  template:
    metadata:
      labels:
        app: demo-react
    spec:
      containers:
      - name: demo-react
        image: smabdullah/demo-react:latest
        env:
        - name: VERSION
          value: "1.00.00" # Replace with your actual API URL
        - name: REACT_APP_APP_VERSION
          value: "V1.2222" # Replace with your actual API URL
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 15