# FILE: .github/workflows/docker-build.yml
name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Generate version number
      id: version
      run: echo "VERSION=$(git describe --tags --always --dirty)" >> $GITHUB_ENV

    - name: Debug Secrets
      run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: List files in the repository
      run: ls -al
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./demo-react
        file: ./demo-react/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: |
          VERSION=${{ env.VERSION }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/demo-react:latest
          ${{ secrets.DOCKER_USERNAME }}/demo-react:${{ env.VERSION }}